---
dependency:
  name: galaxy

driver:
  name: delegated
  options:
    managed: false

platforms:
  - name: localhost

provisioner:
  name: ansible
  inventory:
    host_vars:
      localhost:
        ansible_connection: local

verifier:
  name: ansible
