all:
  children:
    linux:
      hosts:
        192.168.1.100:
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
  vars:
    ansible_python_interpreter: /usr/bin/python3
