name: Test Ansible Playbook Windows

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ansible'
        required: true
        default: 'Playbook'


jobs:
  test-playbook:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Ansible and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible pywinrm

    - name: Configure UTF-8 Encoding
      shell: powershell
      run: |
        $env:PYTHONIOENCODING="utf-8"
        $env:PYTHONUTF8="1"
        [System.Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        chcp 65001
        echo "UTF-8 Encoding Configured"

    - name: Validate Encoding
      shell: powershell
      run: |
        python -c "import locale; print(locale.getpreferredencoding())"

    - name: Configure Ansible Inventory
      run: |
        echo "[windows]" > hosts
        echo "localhost ansible_connection=local" >> hosts

    - name: Run Ansible Playbook
      shell: powershell
      env:
        PYTHONIOENCODING: utf-8
        PYTHONUTF8: "1"
      run: |
        ansible-playbook -i inventory.ini Ansible/PlaybookWindows.yaml 

