name: Test Ansible Playbook Windows

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ansible'
        required: true
        default: 'Playbook'


jobs:
  test-ansible:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install Molecule and dependencies
      - name: Install Molecule and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule molecule[docker] ansible pywinrm

      # Validate Molecule configuration
      - name: Validate Molecule configuration
        run: |
          ls Ansible\molecule.yml
          molecule list

      # Run Molecule tests
      - name: Run Molecule tests
        run: |
          cd Ansible\molecule.yml
          molecule test

