name: Test Ansible Playbook Windows

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ansible'
        required: true
        default: 'Playbook'

jobs:
  test-ansible:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install Molecule and Docker dependencies
      - name: Install Molecule and Docker dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule[docker] ansible pywinrm

      # Set up Ansible inventory for Windows
      - name: Create Ansible inventory
        run: |
          echo '[windows]' > inventory
          echo "localhost ansible_connection=winrm ansible_user=Administrator ansible_password=${{ secrets.WINDOWS_PASSWORD }} ansible_winrm_transport=basic" >> inventory

      # Run Molecule tests
      - name: Run Molecule tests
        run: |
          molecule test
