name: Ansible Playbook Windows 

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ansible'
        required: true
        default: 'Playbook'

jobs:
  configure-windows:
    runs-on: windows-latest
    outputs:
      windows_ip: ${{ steps.get_ip.outputs.ip }}
    steps:
    - name: Configure Static IP
      run: |
        try {
          Write-Host "Fetching the active network interface..."
          $interface = Get-NetAdapter | Where-Object { $_.Status -eq 'Up' } | Select-Object -First 1
          if (-not $interface) {
            Write-Error "No active network interface found. Exiting."
            exit 1
          }

          Write-Host "Configuring static IP for the interface..."
          New-NetIPAddress -InterfaceIndex $interface.ifIndex -IPAddress 192.168.1.100 -PrefixLength 24 -DefaultGateway 192.168.1.1 -ErrorAction Stop

          Write-Host "Setting DNS servers..."
          Set-DnsClientServerAddress -InterfaceIndex $interface.ifIndex -ServerAddresses 8.8.8.8,8.8.4.4 -ErrorAction Stop

          Write-Host "Fetching the configured IP address..."
          $ip = (Get-NetIPAddress -InterfaceIndex $interface.ifIndex -AddressFamily IPv4).IPAddress
          if (-not $ip) {
            Write-Error "Failed to fetch the configured IP address. Exiting."
            exit 1
          }

          Write-Host "Configured IP: $ip"
          echo "::set-output name=ip::$ip"
        } catch {
          Write-Error "An error occurred: $_"
          exit 1
        }

    - name: Configure WinRM
      run: |
        Enable-PSRemoting -Force
        Set-Item wsman:\localhost\Service\Auth\Basic -Value $true
        Set-Item wsman:\localhost\Service\AllowUnencrypted -Value $true
        Restart-Service WinRM

    - name: Open WinRM Port in Firewall
      run: |
        New-NetFirewallRule -DisplayName "Allow WinRM" -Direction Inbound -Protocol TCP -LocalPort 5985 -Action Allow

  run-ansible:
    runs-on: ubuntu-latest
    needs: configure-windows
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Ansible and Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible
        python3 -m pip install --upgrade pip
        pip install pywinrm

    - name: Run Ansible Playbook
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"
      run: |
        ansible-playbook -i Ansible/inventory.ini Ansible/PlaybookWindows.yaml
