name: Ansible Playbook Windows 

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ansible'
        required: true
        default: 'Playbook'

jobs:
  configure-windows:
    runs-on: windows-latest
    outputs:
      windows_ip: ${{ steps.get_ip.outputs.ip }}
    steps:
    - name: Configure Windows Host
      run: |
        # Configuration nécessaire pour activer WinRM
        Enable-PSRemoting -Force
        Set-Item wsman:\localhost\Service\Auth\Basic -Value $true
        Set-Item wsman:\localhost\Service\AllowUnencrypted -Value $true
        Restart-Service WinRM

    - name: Get Windows Machine IP
      id: get_ip
      run: |
        $ip = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.InterfaceAlias -notlike '*Loopback*' }).IPAddress
        echo "::set-output name=ip::$ip"

  run-ansible:
    runs-on: ubuntu-latest
    needs: configure-windows
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Ansible and Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible
        python3 -m pip install --upgrade pip
        pip install pywinrm

    - name: Configure Ansible Inventory
      run: |
        echo "[windows]" > inventory.ini
        echo "${{ needs.configure-windows.outputs.windows_ip }} ansible_connection=winrm ansible_user=Administrator ansible_password=YourPassword ansible_winrm_transport=basic" >> inventory.ini

    - name: Run Ansible Playbook
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"
      run: |
        ansible-playbook -i inventory.ini Ansible/PlaybookWindows.yaml
